name: Create PullRequest
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date +%s > report.txt
      - uses: peter-evans/create-pull-request@v3
