name: dump github context

on:
  workflow_dispatch:
  repository_dispatch:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  registry_package:
  release:
  status:
  watch:
  # workflow_run:

jobs:
  dump_context:
    runs-on: ubuntu-latest
    steps:
      - name: dumpt github context
        run: echo '${{ toJson(github) }}'
