name: dump github context

on:
  workflow_dispatch:
    inputs:
      param1:
        description: required param
        default: required value
        required: true
      param2:
        description: optional param
        default: optional value
        required: false
      condition1:
        description: boolean param
        default: 'false'
        type: boolean
      condition2:
        description: boolean param
        default: 'false'
        type: boolean
  repository_dispatch:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  registry_package:
  release:
  status:
  watch:

env:
  CONDITION_OR_PARAM: ${{ github.event.inputs && (github.event.inputs.condition1 == 'true' || github.event.inputs.condition2 == 'true') }}
  CONDITION_AND_PARAM: ${{ github.event.inputs && (github.event.inputs.condition1 == 'true' && github.event.inputs.condition2 == 'true') }}

jobs:
  dump_context:
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
      - name: print env
        run: printenv
