name: pullrequest comment hook trigger

on:
  issue_comment:

jobs:
  pr_comment_trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    env:
      TRIGGER_PHRASE: test this please
    outputs:
      number: ${{ steps.metadata.outputs.number }}
      body: ${{ steps.metadata.outputs.body }}
      user: ${{ steps.metadata.outputs.user }}
      ref: ${{ steps.metadata.outputs.ref }}
      title: ${{ steps.metadata.outputs.title }}
      description: ${{ steps.metadata.outputs.description }}
      triggerd: ${{ steps.check_trigger_phrase.outputs.triggerd }}
    steps:
      - name: check trigger phrase
        id: check_trigger_phrase
        run: |
          if [[ ${{ github.event.comment.body }} =~ "${env.TRIGGER_PHRASE}" ]]; then
            echo "::set-output name=triggerd::true"
          else
            echo "::set-output name=triggerd::false"
          fi
      - name: metadata
        id: metadata
        if: ${{ steps.check_trigger_phrase.outputs.triggerd }} == 'true'
        run: |
          echo "::set-output name=number::${{ github.event.issue.number }}"
          echo "::set-output name=body::${{ github.event.comment.body }}"
          echo "::set-output name=user::${{ github.event.comment.user.login }}"
          echo "::set-output name=ref::${{ github.event.issue.pull_request.head.ref }}"
          echo "::set-output name=title::${{ github.event.issue.pull_request.title }}"
          echo "::set-output name=description::${{ github.event.issue.pull_request.body }}"

  triggered_action:
    runs-on: ubuntu-latest
    if: ${{ needs.pr_commet_trigger.outputs.triggerd }} == 'true'
    needs:
      - pr_comment_trigger
    steps:
      - name: triggered_action
        run: |
          echo "Triggered!"
          echo "${{ toJson(needs.pr_commet_trigger.outputs) }}"
