name: pullrequest comment hook trigger

on:
  issue_comment:

jobs:
  pr_comment_trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    env:
      TRIGGER_PHRASE: test this please
    outputs:
      triggerd: ${{ steps.check_trigger_phrase.outputs.triggerd }}
      number: ${{ steps.metadata.outputs.number }}
      comment_body: ${{ steps.metadata.outputs.comment_body }}
      user: ${{ steps.metadata.outputs.user }}
      ref: ${{ steps.pull_request.outputs.ref }}
      sha: ${{ steps.pull_request.outputs.sha }}
      title: ${{ steps.pull_request.outputs.title }}
      description: ${{ steps.pull_request.outputs.description }}
    steps:
      - name: check trigger phrase
        id: check_trigger_phrase
        run: |
          if $(echo "${{ github.event.comment.body }}" | grep -e "${{ env.TRIGGER_PHRASE }}" > /dev/null); then
            echo "match trigger phrase"
            echo "::set-output name=triggerd::true"
          else
            echo "::set-output name=triggerd::false"
          fi
      - name: metadata
        id: metadata
        if: steps.check_trigger_phrase.outputs.triggerd == 'true'
        run: |
          echo "::set-output name=number::${{ github.event.issue.number }}"
          echo "::set-output name=comment_body::${{ github.event.comment.body }}"
          echo "::set-output name=user::${{ github.event.comment.user.login }}"
      - name: get pull-request
        id: pull_request
        if: steps.check_trigger_phrase.outputs.triggerd == 'true'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            const pull_request = response.data
            console.log("::set-output name=ref::%s", pull_request.head.ref)
            console.log("::set-output name=sha::%s", pull_request.head.sha)
            console.log("::set-output name=title::%s", pull_request.title)
            console.log("::set-output name=description::%s", pull_request.body)

  triggered_action:
    runs-on: ubuntu-latest
    if: needs.pr_comment_trigger.outputs.triggerd == 'true'
    needs:
      - pr_comment_trigger
    env:
      PR_COMMENT_TRIGGER_OUTPUTS: ${{ toJson(needs.pr_comment_trigger.outputs) }}
    steps:
      - name: dump outputs
        run:  echo "${PR_COMMENT_TRIGGER_OUTPUTS}"
      - name: comment pullrequest
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.pr_comment_trigger.outputs.number }},
              body: `\`\`\`\n${ process.env.PR_COMMENT_TRIGGER_OUTPUTS }\n\`\`\``
            })
